--viewing the data
select * from Supply_Chain_Data


--1. Number of products sold per product type

select [Product type],sum([Number of products sold]) as Products_Sold ,sum(Availability) as Product_Available
from Supply_Chain_Data
group by [Product type]

/* Code Explanation
To calculate the total number of products sold and total number of products available we are using the sum function for individual columns
and grouping by [Product type] to ge these metrics for each product type
*/

--2. What is the distribution of total products sold across the three product types for different cities?

select Location as City, [Product type], sum([Number of products sold]) as Number_of_products_sold
from Supply_Chain_Data
group by Location,[Product type]
order by 1,3 desc

/* Code Explanation
We are using sum function to get the products sold and grouping it first by location and then by product type
so it will give us for a particular location how mauch a particular product type is sold.
This will help in analyzing what type of product is preferred in different locations
*/

--3. Revenue contribution of different product types

select [Product type], sum([Revenue generated]) as Net_Revenue,round(sum([Revenue generated])*100.0/(select sum([Revenue generated]) from Supply_Chain_Data),2) as Revenue_percentage
from Supply_Chain_Data
group by [Product type]

/* Code Explanation
Using the sum function on [Revenue generated] column we are getting total revenue generated for each product type (as we are grouping by product type)
To calculate the percentage-wise contribution of the revenue, we are dividing the revenue generated by product type with total revenue generated irrespective of product type 
which we re calculating using the subquery (select sum([Revenue generated]) from Supply_Chain_Data)
Finally multiplying the fraction with 100.0 to get the value as percentage and rounding it to two decimal places using round function
*/

--4. customer demographic distribution of products- which customer demographics are major buyers for different product_types

;with customer_demographics as(
select [Product type], [Customer demographics], sum([Number of products sold]) as sold_units
from Supply_Chain_Data
group by [Product type], [Customer demographics]
--order by 1,3 desc
),
ranking as(
select [Product type], [Customer demographics], sold_units, ROW_NUMBER()over(partition by [Product type] order by sold_units desc) as ranks
from customer_demographics
)
select [Product type], [Customer demographics], sold_units from ranking
where ranks=1

/* Code Explanation
For this question we are creating a CTE (Common Table Expression) named customer_demographics , in which we are getting the number of products sold for each product type and
for each customer demographic.
Again we create a CTE named ranking in which we use the window function ROW_NUMBER to assing the rw number to each row according to Product type and ordering by units sold 
i.e each product type will have its row umber individually and the customer demographics that has the highest units sold for that particular product will be ranked as 1 and so on.
Finally we select the custmer graphich for each product type whose ranking is 1 i.e it has most units sold.
*/

--5. Supplier from which the most quantities are ordered for each product type

;with suppliers_count as(select [Product type], [Supplier name], sum([Order quantities]) as Counts
from Supply_Chain_Data
group by [Product type],[Supplier name]
--order by 1,3 desc
)
select [Product type], [Supplier name], counts
from suppliers_count
where counts in (select max(counts)over(partition by [Product type]) from suppliers_count)

/* Code Explanation
We are creating a CTE first, named suppliers_count in which we are getting the total orders for each product type provided by different suppliers by using sum function 
and grouping by [Product type],[Supplier name]. 
Then we are selecting [Product type], [Supplier name], counts (number of quantitites ordered) from the CTE and giving the condition that the value of counts should be maximum value
of the quantities order for that particular product, which we are calculating using the subqury (select max(counts)over(partition by [Product type]) from suppliers_count) in which
we have used the used max function and partitioned it over product type to ge the maximum products sold for each product as mentioned above.
*/

--6. Which shipping carrier is best for different product types

;with shipping as (
select [Product type], [Shipping carriers], round(avg([Shipping costs]),2) as avg_shipping_cost
from Supply_Chain_Data
group by [Product type], [Shipping carriers]
--order by [Product type], 3 asc
)
select [Product type], [Shipping carriers], avg_shipping_cost
from shipping
where avg_shipping_cost in (select min(avg_shipping_cost)over(partition by [Product type]) from shipping)
order by 1

/* Code Explanation
Created the CTE named shipping, in which we found the average shipping cost of different carriers for different product types using avg function 
and round it to 2 decimal places and grouped by  [Product type], [Shipping carriers].
Now, to get the shipping carrier with the minimum shipping cost we give the where condition that the avg_shipping_cost is minimum shipping cost for the particular product type,
to calculate that we use subquery (select min(avg_shipping_cost)over(partition by [Product type]) from shipping) in which we are using the minimum function to get the minimum
avg_shipping_cost for each product type by giving the partition by command.
*/



--7. The Average lead time and Average Manufacturing Costs for all products of the company

select [Product type], round(avg([Lead time]),2) as average_lead_time, round(avg([Manufacturing costs]),2) as average_manufacturing_cost
from Supply_Chain_Data
group by [Product type]

/* Code Explanation
In this to we are using average function to find average lead ime and average manufacturing costs respectively 
and rounding  the values to 2 decimal places using round function
finally grouping by [Product type] to get the above metrics for each product type
*/

--8. Percentage Cost distribution by transportation mode

select [Transportation modes], round(sum(Costs)*100.0/(select sum(Costs) from Supply_Chain_Data),2) as cost_percentage_distribution
from Supply_Chain_Data
group by [Transportation modes]
order by 2 desc

/* Code Explanation
First we are adding the costs according to the [Transportation modes] and then we are divind it by total transporation cost irrespective of mode which we are calculating 
using the folowing sub-query  "select sum(Costs) from Supply_Chain_Data" .
To get the value as percentage we are multiplying the fraction by 100.0 and finally to round it upto two decimal places using round function
We are ordering by the cost_percetage_distribution in decending order to get the results
*/


--9. Average defect rate by product type

select [Product type], round(avg([Defect rates]),2) as avg_defect_rate
from Supply_Chain_Data
group by [Product type]

/* Code Explanation
Using the AVG function we are finding the average defect rates and then by applying round(avg([Defect rates]),2)
we are rounding the value to two decimal places.
We are grouping by [Product type] to get the average defect rates for each product type
*/

-- 10. Pass/Fail/Pending count different product type

select [Product type], sum(case when [Inspection results] ='Pending' then 1 else 0 end) as Pending,
sum(case when [Inspection results]='Pass' then 1 else 0 end) as Pass,
sum(case when [Inspection results] ='Fail' then 1 else 0 end)  as Fail
from Supply_Chain_Data
group by [Product type]

/* Code Explanation
Using the case statement we are giving the condition i.e when [Inspection results] ='Pending' we are giving it 1 as value and if not then 0, 
so when we give sum fucntion to this case statement then we will get the total pending count, 
same logic is applied to when [Inspection results]='Pass' and  when [Inspection results] ='Fail'
since we are grouping it by [Product type], we will get the Pending, Pass, Fail count of each product type
*/



